logging:
  level:
    org.springframework.security: DEBUG
    nz.co.ritc.classyfindz: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG    
#JDBC
jdbc:
  driverClassName: 'com.mysql.jdbc.Driver'
  username: m1cwdev1
  password: nnzj58TYM
  url: 'jdbc:mysql://db-1cw-dev-1.cq2j9lvsqvyg.us-west-2.rds.amazonaws.com:3306/db_1cw_dev_1'
  
#Hibernate Configuration
hibernate:
  dialect: 'org.hibernate.dialect.H2Dialect'
  hbm2ddl:
    auto: create-drop
  ejb:
    naming_strategy: 'org.hibernate.cfg.ImprovedNamingStrategy'
  show_sql: false
  format_sql: true 